//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TerminalDeViale.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recorrido
    {
        public int id { get; set; }
        public Nullable<bool> estado { get; set; }
        public Nullable<System.DateTime> fecha_alta { get; set; }
        public Nullable<System.DateTime> fecha_baja { get; set; }
        public int id_localidad { get; set; }
        public int id_empresa { get; set; }
        public int id_horario { get; set; }
        public string usuario_baja { get; set; }
        public string usuario_alta { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual Horario Horario { get; set; }
        public virtual Localidad Localidad { get; set; }
    }
}
